### ISSUE TITLE
question for solid

### ISSUE THREAD

**Issue by jiangwei7480** [marat1961/Oz-Solid#20]
hi，hello
  happen a question
constructor TExprParser.From(const inp: string);
var
  n: Integer;
begin
  n := inp.Length - 1;
  Check(n >= 0, 'TExprParser: empty expr');
  it := PChar(inp);
  stack := TsgStack<TSymbol>.From(200);
  NextChar;
end;

from<> params count miss.

**Comment by marat1961** [comment]
fixed by "restoring compilability after changes in the SGL project"
